spring:
  application:
    name: feign-server
server:
  port: 8765

feign:
  hystrix:
    enabled: true

#turbine:
#  app-config: service-customer
#  combine-host-port: true
#  cluster-name-expression: "'default'"
