language: java

branches:
  only:
    - master

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn -DskipTests=true clean install

after_success:
  - mvn clean test jacoco:report
  - mvn coveralls:report -DrepoToken="${RepoToken}"
