server:
  port: 9090

spring:
  application:
    name: api-gateway
  profiles:
    active: @profiles.active@
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    # 表示拉取服务注册信息的间隔
    registry-fetch-interval-seconds: 5
  instance:
    # 表示向server端发送心跳频率
    lease-renewal-interval-in-seconds: 5
    # 表示等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

zuul:
  # 禁止服务自动添加
  ignored-services: '*'
  routes:
    api-a:
      path: /customer/**
      service-id: service-customer
    api-b:
      path: /producer/**
      service-id: service-producer
  # 开启重试功能
  retryable: true
#    # 在zuul和服务间增加feign只会增加通讯消耗，并不推荐
#    api-c:
#      path: /feign/**
#      # 由网关分发到feign，再经feign负载均衡
#      service-id: feign-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always