server:
  port: 9090

spring:
  application:
    name: api-gateway
  profiles:
    active: @profiles.active@
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true

zuul:
  # 禁止服务自动添加
  ignored-services: '*'
  routes:
    api-a:
      path: /customer/**
      service-id: service-customer
    api-b:
      path: /producer/**
      service-id: service-producer
  # 开启重试功能
  retryable: true
#    # 在zuul和服务间增加feign只会增加通讯消耗，并不推荐
#    api-c:
#      path: /feign/**
#      # 由网关分发到feign，再经feign负载均衡
#      service-id: feign-server