server:
  port: 8100

spring:
  application:
    name: service-producer
  profiles:
    active: @profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always