server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles:
    # 不加单引号会报错
    active: '@profiles.active@'

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    # 表示是否将自己注册到Eureka Server上，默认为true
    register-with-eureka: false
    # 表示是否从Eureka Server上获取注册信息，默认为true
    fetch-registry: false
  server:
    # 自我保护机制
    enable-self-preservation: true

